[tool.poetry]
name = "diabetes-predictor"
version = "0.1.0"
description = ""
authors = ["your-name"]

[tool.poetry.dependencies]
python = "3.11.*"
streamlit = "^1.24"
scikit-learn = "^1.3"
imbalanced-learn = "^0.11"
pandas = "^2.1"
numpy = "^1.27"
matplotlib = "^3.8"
gTTS = "^2.5"
